const enum IpcChannel {
  APP_VERSION = "APP_VERSION",
  GET_USER_PREFERENCES = "GET_USER_PREFERENCES",
  SETTINGS_OPEN_CONFIRM_PROMPT = "SETTINGS_OPEN_CONFIRM_PROMPT",
  SETTINGS_OPEN_DIR_DIALOG = "SETTINGS_OPEN_DIR_DIALOG",
  SETTINGS_SAVE = "SETTINGS_SAVE",
}

export default IpcChannel;
