const enum IpcChannel {
  APP_VERSION = "APP_VERSION",
  GET_USER_PREFERENCES = "GET_USER_PREFERENCES",
  ON_CLOSE_BUTTON_CLICK = "ON_CLOSE_BUTTON_CLICK",
  SAVE_SETTINGS_AND_CLOSE = "SAVE_SETTINGS_AND_CLOSE",
  SETTINGS_OPEN_CONFIRM_PROMPT = "SETTINGS_OPEN_CONFIRM_PROMPT",
  SETTINGS_OPEN_DIR_DIALOG = "SETTINGS_OPEN_DIR_DIALOG",
}

export default IpcChannel;
