const enum IpcChannel {
  APP_VERSION = "APP_VERSION",
  CHECK_CAMERA_ACCESS = "CHECK_CAMERA_ACCESS",
  GET_USER_PREFERENCES = "GET_USER_PREFERENCES",
  LOG_RENDERER = "LOG_RENDERER",
  ON_CLOSE_BUTTON_CLICK = "ON_CLOSE_BUTTON_CLICK",
  SAVE_SETTINGS_AND_CLOSE = "SAVE_SETTINGS_AND_CLOSE",
  OPEN_CONFIRM_PROMPT = "OPEN_CONFIRM_PROMPT",
  OPEN_DIR_DIALOG = "OPEN_DIR_DIALOG",
}

export default IpcChannel;
